# Generated by Django 5.2.5 on 2025-08-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketpricing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ticketpricing',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
    ]
