# Generated by Django 5.2.5 on 2025-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_ticketpricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpricing',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketpricing',
            name='ticket_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='ticketpricing',
            unique_together={('event', 'ticket_type')},
        ),
    ]
